/**
 * WordPress Service
 * Handles interaction with WordPress REST API
 */
const axios = require('axios');
const FormData = require('form-data');

// Ensure required environment variables are set
if (!process.env.WP_URL || !process.env.WP_USER || !process.env.WP_APP_PASSWORD) {
  console.error('Missing WordPress configuration in .env');
}

const wpAuth = Buffer.from(`${process.env.WP_USER}:${process.env.WP_APP_PASSWORD}`).toString('base64');
const wpInstance = axios.create({
  baseURL: `${process.env.WP_URL}/wp-json/wp/v2`,
  headers: {
    Authorization: `Basic ${wpAuth}`,
    'User-Agent': 'M365-App-Integration'
  }
});

async function getCategories() {
  try {
    const response = await wpInstance.get('/categories');
    return response.data.sort((a, b) => a.name.localeCompare(b.name));
  } catch (error) {
    console.error('Error fetching WP categories:', error.response?.data || error.message);
    return [];
  }
}

async function uploadMedia(file) {
  try {
    const formData = new FormData();
    formData.append('file', file.buffer, { filename: file.originalname });

    const response = await wpInstance.post('/media', formData, {
      headers: formData.getHeaders()
    });
    return response.data.id;
  } catch (error) {
    console.error('Error uploading to WP media:', error.response?.data || error.message);
    throw new Error('Failed to upload file to WordPress');
  }
}

async function createPost(title, content, categoryId, mediaIds) {
  try {
    const postData = {
      title,
      content, // HTML content generated by TinyMCE, Gutenberg handles this well
      categories: [categoryId],
      status: 'draft' // Default to draft for safety
    };

    if (mediaIds && mediaIds.length > 0) {
      postData.featured_media = mediaIds[0];
    }

    const response = await wpInstance.post('/posts', postData);
    return response.data;
  } catch (error) {
    console.error('Error creating WP post:', error.response?.data || error.message);
    throw new Error('Failed to create post in WordPress');
  }
}

module.exports = { getCategories, uploadMedia, createPost };
